QT += widgets \

HEADERS += \
    Controleur.h \
    Game.h \
    InfoMenu.h \
    Jeu.h \
    Joueur.h \
    Meeple.h \
    Pioche.h \
    Plateau.h \
    StartMenu.h \
    Tuile.h \
    ViewBoard.h \
    ViewMeeple.h \
    ViewTile.h

SOURCES += \
    Controleur.cpp \
    Game.cpp \
    InfoMenu.cpp \
    Jeu.cpp \
    Joueur.cpp \
    Pioche.cpp \
    Plateau.cpp \
    StartMenu.cpp \
    Tuile.cpp \
    ViewBoard.cpp \
    ViewMeeple.cpp \
    ViewTile.cpp \
    ensembleTuiles.cpp \
    main.cpp \

DISTFILES += \
    CarLogo.ico \
    Images/CarLogo.ico \
    Images/LogoOrg.png \
    Images/Title.png \
    Images/VisualTiles/0.png \
    Images/VisualTiles/1.png \
    Images/VisualTiles/10.png \
    Images/VisualTiles/11.png \
    Images/VisualTiles/12.png \
    Images/VisualTiles/13.png \
    Images/VisualTiles/14.png \
    Images/VisualTiles/15.png \
    Images/VisualTiles/16.png \
    Images/VisualTiles/17.png \
    Images/VisualTiles/18.png \
    Images/VisualTiles/19.png \
    Images/VisualTiles/2.png \
    Images/VisualTiles/20.png \
    Images/VisualTiles/21.png \
    Images/VisualTiles/22.png \
    Images/VisualTiles/23.png \
    Images/VisualTiles/24.png \
    Images/VisualTiles/25.png \
    Images/VisualTiles/26.png \
    Images/VisualTiles/27.png \
    Images/VisualTiles/28.png \
    Images/VisualTiles/29.png \
    Images/VisualTiles/3.png \
    Images/VisualTiles/30.png \
    Images/VisualTiles/31.png \
    Images/VisualTiles/32.png \
    Images/VisualTiles/33.png \
    Images/VisualTiles/34.png \
    Images/VisualTiles/35.png \
    Images/VisualTiles/36.png \
    Images/VisualTiles/37.png \
    Images/VisualTiles/38.png \
    Images/VisualTiles/39.png \
    Images/VisualTiles/4.png \
    Images/VisualTiles/5.png \
    Images/VisualTiles/6.png \
    Images/VisualTiles/7.png \
    Images/VisualTiles/72.png \
    Images/VisualTiles/73.png \
    Images/VisualTiles/74.png \
    Images/VisualTiles/75.png \
    Images/VisualTiles/76.png \
    Images/VisualTiles/77.png \
    Images/VisualTiles/78.png \
    Images/VisualTiles/79.png \
    Images/VisualTiles/8.png \
    Images/VisualTiles/80.png \
    Images/VisualTiles/81.png \
    Images/VisualTiles/82.png \
    Images/VisualTiles/83.png \
    Images/VisualTiles/9.png \
    Images/VisualTiles/A.png \
    Images/VisualTiles/B.png \
    Images/VisualTiles/Basic/A.png \
    Images/VisualTiles/Basic/B.png \
    Images/VisualTiles/Basic/C.png \
    Images/VisualTiles/Basic/D.png \
    Images/VisualTiles/Basic/DEF.png \
    Images/VisualTiles/Basic/E.png \
    Images/VisualTiles/Basic/F.png \
    Images/VisualTiles/Basic/G.png \
    Images/VisualTiles/Basic/H.png \
    Images/VisualTiles/Basic/I.png \
    Images/VisualTiles/Basic/J.png \
    Images/VisualTiles/Basic/K.png \
    Images/VisualTiles/Basic/L.png \
    Images/VisualTiles/Basic/M.png \
    Images/VisualTiles/Basic/N.png \
    Images/VisualTiles/Basic/O.png \
    Images/VisualTiles/Basic/P.png \
    Images/VisualTiles/Basic/POS.png \
    Images/VisualTiles/Basic/Q.png \
    Images/VisualTiles/Basic/R.png \
    Images/VisualTiles/Basic/S.png \
    Images/VisualTiles/Basic/SEL.png \
    Images/VisualTiles/Basic/T.png \
    Images/VisualTiles/Basic/U.png \
    Images/VisualTiles/Basic/V.png \
    Images/VisualTiles/Basic/W.png \
    Images/VisualTiles/Basic/X.png \
    Images/VisualTiles/C.png \
    Images/VisualTiles/Cathedral/E1.png \
    Images/VisualTiles/Cathedral/E2.png \
    Images/VisualTiles/Cathedral/E3.png \
    Images/VisualTiles/Cathedral/ED.png \
    Images/VisualTiles/Cathedral/EE.png \
    Images/VisualTiles/Cathedral/EF.png \
    Images/VisualTiles/Cathedral/EG.png \
    Images/VisualTiles/Cathedral/EH.png \
    Images/VisualTiles/Cathedral/EI.png \
    Images/VisualTiles/Cathedral/EJ.png \
    Images/VisualTiles/Cathedral/EK.png \
    Images/VisualTiles/Cathedral/EL.png \
    Images/VisualTiles/Cathedral/EM.png \
    Images/VisualTiles/Cathedral/EN.png \
    Images/VisualTiles/Cathedral/EO.png \
    Images/VisualTiles/Cathedral/EP.png \
    Images/VisualTiles/Cathedral/EQ.png \
    Images/VisualTiles/D.png \
    Images/VisualTiles/DEF.png \
    Images/VisualTiles/E.png \
    Images/VisualTiles/E1.png \
    Images/VisualTiles/E2.png \
    Images/VisualTiles/E3.png \
    Images/VisualTiles/ED.png \
    Images/VisualTiles/EE.png \
    Images/VisualTiles/EF.png \
    Images/VisualTiles/EG.png \
    Images/VisualTiles/EH.png \
    Images/VisualTiles/EI.png \
    Images/VisualTiles/EJ.png \
    Images/VisualTiles/EK.png \
    Images/VisualTiles/EL.png \
    Images/VisualTiles/EM.png \
    Images/VisualTiles/EN.png \
    Images/VisualTiles/EO.png \
    Images/VisualTiles/EP.png \
    Images/VisualTiles/EQ.png \
    Images/VisualTiles/F.png \
    Images/VisualTiles/F1.png \
    Images/VisualTiles/F10.png \
    Images/VisualTiles/F11.png \
    Images/VisualTiles/F12.png \
    Images/VisualTiles/F2.png \
    Images/VisualTiles/F3.png \
    Images/VisualTiles/F4.png \
    Images/VisualTiles/F5.png \
    Images/VisualTiles/F6.png \
    Images/VisualTiles/F7.png \
    Images/VisualTiles/F8.png \
    Images/VisualTiles/F9.png \
    Images/VisualTiles/G.png \
    Images/VisualTiles/H.png \
    Images/VisualTiles/I.png \
    Images/VisualTiles/J.png \
    Images/VisualTiles/K.png \
    Images/VisualTiles/L.png \
    Images/VisualTiles/M.png \
    Images/VisualTiles/N.png \
    Images/VisualTiles/O.png \
    Images/VisualTiles/P.png \
    Images/VisualTiles/POS.png \
    Images/VisualTiles/Q.png \
    Images/VisualTiles/R.png \
    Images/VisualTiles/River/F1.png \
    Images/VisualTiles/River/F10.png \
    Images/VisualTiles/River/F11.png \
    Images/VisualTiles/River/F12.png \
    Images/VisualTiles/River/F2.png \
    Images/VisualTiles/River/F3.png \
    Images/VisualTiles/River/F4.png \
    Images/VisualTiles/River/F5.png \
    Images/VisualTiles/River/F6.png \
    Images/VisualTiles/River/F7.png \
    Images/VisualTiles/River/F8.png \
    Images/VisualTiles/River/F9.png \
    Images/VisualTiles/S.png \
    Images/VisualTiles/SEL.png \
    Images/VisualTiles/Saved/Ensemble des tuiles.jpeg \
    Images/VisualTiles/Saved/Ensemble des tuiles.jpeg \
    Images/VisualTiles/Saved/Répertoire des tuiles.xlsx \
    Images/VisualTiles/Saved/Répertoire des tuiles.xlsx \
    Images/VisualTiles/T.png \
    Images/VisualTiles/U.png \
    Images/VisualTiles/V.png \
    Images/VisualTiles/W.png \
    Images/VisualTiles/X.png \
    Images/back.jpg \
    Logo.png \
    LogoOrg.png \
    Test.pro.user \
    Title.png \
    back.jpg

TARGET = Carcassonne\

RESOURCES += \
    images.qrc

